

    .zp

        R0:        .ds 2
        R1:        .ds 2
        R2:        .ds 2
        R3:        .ds 2
        R4:        .ds 2
        R5:        .ds 2
        R6:        .ds 2
        R7:        .ds 2
        R8:        .ds 2
        A0:        .ds 2
        A1:        .ds 2
        A2:        .ds 2
        A3:        .ds 2
        A4:        .ds 2
        A5:        .ds 2
        A6:        .ds 2
        A7:        .ds 2
        A8:        .ds 2
        D0:        .ds 2
        D1:        .ds 2
        D2:        .ds 2
        D3:        .ds 2
        D4:        .ds 2
        D5:        .ds 2
        D6:        .ds 2
        D7:        .ds 2
        D8:        .ds 2
        M0:        .ds 1      ;MPR 2
        M1:        .ds 1      ;MPR 3
        M2:        .ds 1      ;MPR 4
        M3:        .ds 1      ;MPR 5
        M4:        .ds 1      ;MPR 6
        M5:        .ds 1      ;MPR 7

        EAX0:      .ds 4
        EAX1:      .ds 4
        EAX2:      .ds 4
        EAX3:      .ds 4

A0.l  .equ  A0
A0.h  .equ  A0+1
A1.l  .equ  A1
A1.h  .equ  A1+1
A2.l  .equ  A2
A2.h  .equ  A2+1
A3.l  .equ  A3
A3.h  .equ  A3+1
A4.l  .equ  A4
A4.h  .equ  A4+1
A5.l  .equ  A5
A5.h  .equ  A5+1
A6.l  .equ  A6
A6.h  .equ  A6+1
A7.l  .equ  A7
A7.h  .equ  A7+1

D0.l  .equ  D0
D0.h  .equ  D0+1
D1.l  .equ  D1
D1.h  .equ  D1+1
D2.l  .equ  D2
D2.h  .equ  D2+1
D3.l  .equ  D3
D3.h  .equ  D3+1
D4.l  .equ  D4
D4.h  .equ  D4+1
D5.l  .equ  D5
D5.h  .equ  D5+1
D6.l  .equ  D6
D6.h  .equ  D6+1
D7.l  .equ  D7
D7.h  .equ  D7+1

R0.l  .equ  R0
R0.h  .equ  R0+1
R1.l  .equ  R1
R1.h  .equ  R1+1
R2.l  .equ  R2
R2.h  .equ  R2+1
R3.l  .equ  R3
R3.h  .equ  R3+1
R4.l  .equ  R4
R4.h  .equ  R4+1
R5.l  .equ  R5
R5.h  .equ  R5+1
R6.l  .equ  R6
R6.h  .equ  R6+1
R7.l  .equ  R7
R7.h  .equ  R7+1

EAX0.l = EAX0
EAX0.m = EAX0+1
EAX0.h = EAX0+2
EAX0.u = EAX0+3

EAX1.l = EAX1
EAX1.m = EAX1+1
EAX1.h = EAX1+2
EAX1.u = EAX1+3

EAX2.l = EAX2
EAX2.m = EAX2+1
EAX2.h = EAX2+2
EAX2.u = EAX2+3

EAX3.l = EAX3
EAX3.m = EAX3+1
EAX3.h = EAX3+2
EAX3.u = EAX3+3


    .bss

        int__dma_block:         .ds 1+2+2+2+1

int__dma_block.type   = int__dma_block
int__dma_block.source = int__dma_block + 1
int__dma_block.dest   = int__dma_block + 1 + 2
int__dma_block.len    = int__dma_block + 1 + 2 + 2
int__dma_block.rts    = int__dma_block + 1 + 2 + 2 + 2

