    .bss

    songTrack:          .ds 1
    songTrackLen:       .ds 1

    scrollDirection:    .ds 1

    ghost.pos.x:        .ds 2
    ghost.pos.y:        .ds 2

    ghostOld.pos.x:     .ds 2
    ghostOld.pos.y:     .ds 2

    screen.tile.addr:   .ds 2            

    ghostFrame:         .ds 1
    ghostFrameOld:      .ds 1

    ghostSet:           .ds 1

    frameDelayCounter:  .ds 1
    frameDelayDiv:      .ds 1
